export enum Cards {
  'ZERO' = 0,
  'HALF' = 0.5,
  'ONE' = 1,
  'TWO' = 2,
  'THREE' = 3,
  'FIVE' = 5,
  'EIGHT' = 8,
  'THIRTEEN' = 13,
  'TWENTY' = 20,
  'FORTY' = 40,
  'HUNDRED' = 100,
  'QUESTION_MARK' = '?',
  'COFFEE' = 'coffee',
  'INFINITE' = 'infinite',
}
